title: Blog Bibliotheks- und Archivinformatik
author: Lara Pfister
email: lara.pfister@stud.fhgr.ch
description: > # this means to ignore newlines
Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS 2021
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
